USE MobileAppRetail_DB;

-- 2.1.1 List all databases on the server
SELECT name AS databases
FROM sys.databases;
GO

-- 2.1.2 Quick summary counts
SELECT 
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE') AS NumTables,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.VIEWS) AS NumViews,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS) AS NumColumns,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY') AS NumPrimaryKeys,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS) AS NumForeignKeys;
GO

-- 2.1.3 List all tables
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME;
GO

-- 2.1.4 Table summary with columns count & row count
SELECT 
    t.TABLE_SCHEMA,
    t.TABLE_NAME,
    COUNT(c.COLUMN_NAME) AS NumColumns,
    ISNULL(SUM(p.rows), 0) AS ApproxRowCount
FROM INFORMATION_SCHEMA.TABLES t
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c 
    ON c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME
LEFT JOIN sys.tables st 
    ON st.name = t.TABLE_NAME
LEFT JOIN sys.partitions p 
    ON p.object_id = st.object_id AND p.index_id IN (0,1)
WHERE t.TABLE_TYPE = 'BASE TABLE'
GROUP BY t.TABLE_SCHEMA, t.TABLE_NAME
ORDER BY t.TABLE_SCHEMA, t.TABLE_NAME;
GO

-- 2.1.5 List all views
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS
ORDER BY TABLE_SCHEMA, TABLE_NAME;
GO

-- 2.1.6 Columns overview
SELECT 
	TABLE_SCHEMA,
	TABLE_NAME,
	COLUMN_NAME, 
	IS_NULLABLE,
	DATA_TYPE,
	CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME;
GO

-- 2.1.7 Inspect a specific table's columns
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'user'
ORDER BY ORDINAL_POSITION;
GO

-- 2.1.8 Primary keys
SELECT 
    TC.TABLE_SCHEMA,
    TC.TABLE_NAME,
    KU.COLUMN_NAME AS PrimaryKeyColumn
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KU
    ON TC.CONSTRAINT_NAME = KU.CONSTRAINT_NAME
WHERE TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY TC.TABLE_SCHEMA, TC.TABLE_NAME, KU.ORDINAL_POSITION;
GO

-- 2.1.9 Foreign keys
SELECT 
    FK.TABLE_SCHEMA AS ForeignSchema,
    FK.TABLE_NAME AS ForeignTable,
    CU.COLUMN_NAME AS ForeignKeyColumn,
    PK.TABLE_SCHEMA AS PrimarySchema,
    PK.TABLE_NAME AS PrimaryTable,
    PT.COLUMN_NAME AS PrimaryKeyColumn
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK 
    ON RC.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK 
    ON RC.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU 
    ON RC.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE PT 
    ON PK.CONSTRAINT_NAME = PT.CONSTRAINT_NAME
ORDER BY FK.TABLE_SCHEMA, FK.TABLE_NAME;
GO
